### ISSUE TITLE
Text overlap issue with copyleft symbol

### ISSUE THREAD

**Issue by stordoff** [edent/Extended-Hyperlegible#1]
I noticed this in your [blog post](https://shkspr.mobi/blog/2022/08/an-update-to-the-atkinson-hyperlegible-font/) - the copyleft symbol is overlapped by the following full stop. I've thrown together a quick HTML/CSS test case showing the issue compared to another font:

![image](https://github.com/edent/Extended-Hyperlegible/assets/1475771/0b8f2ad9-521b-44c5-a45d-95b46c854c4b)

````
<style>
@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+Symbols');
@font-face {
  font-family: 'hyper';
  src:  url('Extended-Hyperlegible-Regular-103.woff2') format('woff2');
};
</style>

<p style="font-family:'hyper'">Extended Hyperlegible: Copyleft symbol 🄯.</p>
<p style="font-family:'Noto Sans Symbols'">Noto Sans Symbols: Copyleft symbol 🄯.</p>

<p style="font-family:'hyper'">Extended Hyperlegible: 🄯2023</p>
<p style="font-family:'Noto Sans Symbols'">Noto Sans Symbols: 🄯2023</p>
````

**Comment by edent** [comment]
Please can you let me know which browser you're using? I've tried it in Chrome, Firefox, and WebKit - and I don't see the error.

**Comment by stordoff** [comment]
Apologies, I completely overlooked that there might be browser differences. Tried it in a few different ones:

- Chrome 119.0.6045.124 on Windows 11 x64 - renders as in the screenshot above
- Chrome 120.0.6099.18 (beta) on Windows 11 x64 - renders as in the screenshot above
- Edge 119.0.2151.58 on Windows 11 x64 - renders as in the screenshot above
- Firefox 119.0.1 on Windows 11 x64 - renders properly
- Safari on iOS 17.1.1 (iPhone 11) - renders properly

**Comment by edent** [comment]
Thanks for the info. I think I've found the issue - but it is concerning that the Chromium engine on Windows is the only browser which chokes on this.

I'll attempt a fix here, but could you raise a bug with them please?

**Comment by edent** [comment]
@stordoff could you please try with this file and let me know if it works on Windows? [ExtendedHyperlegible-Regular-test.zip](https://github.com/edent/Extended-Hyperlegible/files/13362857/ExtendedHyperlegible-Regular-test.zip)

Thanks!

**Comment by stordoff** [comment]
@edent Only had a few minutes to test this due to a family emergency, so only tried a few browser versions, but it appears to render properly in Chrome 119/Edge 119/Firefox 119 (Chrome shown below). 👍
![Screenshot 2023-11-15 153753](https://github.com/edent/Extended-Hyperlegible/assets/1475771/a6410b58-4a80-4aee-930c-c3ede53309c4)

**Comment by edent** [comment]
Thanks - I'll release an updated version of the font shortly.
